config/routes.rb
Tempo::Application.routes.draw do
  get "welcome/index"
  
  root :to => "welcome#index"
  
  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout
  
  match "/sonata" => "email#read", :as => :sonata
  match "/learn"  => "welcome#learn", :as => :learn
  

end

app/models/sender.rb
class Sender
  attr_accessor :name, :dates
  
  def initialize(name)
    self.name = name
    self.dates = []
  end
  
  def <<(time)
    self.dates << time.to_date
  end
  
  def sends_by_week
    d = self.dates.group_by{ |d| d.cweek }
    puts d
    d
  end
  
  def count
    self.dates.count
  end
  
  def uniq
    self.dates.uniq.count
  end
  
  # .strftime("%Y-%-m-%-d")
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/email_controller.rb
class EmailController < ApplicationController
  def read; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    session[:oauth] = auth.credentials.token
    session[:email] = auth.info.email
    redirect_to sonata_url
  end

  def destroy
    session[:oauth] = nil
    session[:email] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    puts session[:oauth]
  end
  
  def learn
    @title = "Learn More"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    session[:oauth] and session[:email]
  end
end

app/helpers/email_helper.rb
module EmailHelper
  def websocket_session
    "login##{session[:email]}:#{session[:oauth]}".html_safe
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tempo<%= @title ? " | "+@title : ""%></title>
  <%= stylesheet_link_tag    :application %>
  <%= javascript_include_tag :application %>
  <script type="text/javascript" src="//use.typekit.net/gdc1igv.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="content">
    <%= yield %>
    <ul id="footer">
      <% if current_page?(learn_path) %>
        <li><a href="/">Home</a></li>
      <% else %>
        <li><a href="/learn">Learn More</a></li>
      <% end%>
      <li><a href="https://twitter.com/teej_m">@teej_m</a></li>
      <li><a href="http://teejm.com">teejm.com</a></li>
      <% if logged_in? %>
      <li><a href="/signout">Sign out</a></li>
      <% end %>
    </ul>
  </div>
  
  
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-40678962-1']);
    _gaq.push(['_setLocalGifPath', 'http://localhost:3001/ping.gif']);
    _gaq.push(['_setLocalRemoteServerMode']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
</body>
</html>

app/views/welcome/index.html.erb
<div id="welcome">
  <h1>Tempo</h1>
  <div class="tagline">The simplest way to wrangle your inbox</div>
  <% if logged_in? %>
    <a class="btn try-button" href="/sonata">See Your Results</a>
  <% else %>
    <a class="btn try-button" href="/auth/google_oauth2">Try It Now</a>
  <% end %>
  or <a href="/learn">Learn More</a>
</div>


<!-- Adiago, Mezzo, Presto -->

app/views/welcome/learn.html.erb
<div id="learn">
  <h1 id="logo"><a href="/">Tempo</a></h1>
  <div class="explanation">
    <strong>Tempo</strong> is a simple app I made to better understand where my email was coming from.
    
    <h3>How It Works</h3>
    
    <ul>
      <li>You authorize Tempo to access your email via IMAP</li>
      <li>Tempo reads the headers of every email you've been sent in the last 4 weeks</li>
      <li>You get a visualization like this:</li>
      <%= image_tag('screenshot.png') %>
      <li>That's it!</li>
    </ul>
    
    <h3>Security &amp; Privacy</h3>
    Giving an app access to your email can be scary.  That's why I'm fully disclosing my usage of your account.
    <ul>
      <li>After you authorize Tempo, your email address and OAuth token get saved in a session</li>
      <li>The app uses these credentials to access GMail via IMAP</li>
      <li>When you use Tempo for the first time, I log the first 5 characters of your email address</li>
      <li>I use the &ldquo;PEEK&rdquo; protocol, which means none of your mail get's marked as read</li>
      <li>Tempo only asks for an email's uid and its &ldquo;From:&rdquo; header</li>
      <li>Tempo will only check the last 4 weeks of email in your inbox</li>
    </ul>
    <p>
    After you've tried Tempo, feel free to <a href="/signout">sign out</a>, this will delete any trace of your account.  You can also <a href="https://accounts.google.com/b/0/IssuedAuthSubTokens?hl=en_US">revoke Tempo's access</a> through Google.  And for those who are interested, you can browse the source code <a href="https://github.com/teej/tempo">on Github</a>.
    </p>
    <p>I hope you enjoy Tempo!  If you did, please share it with others.</p>
  </div>
</div>